/**
 * Prebuild script: merges config/config.yml + config/maps.yml + MAPBOX_TOKEN
 * into frontend/public/config.json for the static frontend to fetch.
 *
 * Token resolution order:
 *   1. MAPBOX_TOKEN environment variable (set in shell or GitHub Actions secret)
 *   2. MAPBOX_TOKEN in project root .env file
 *
 * Edit config/config.yml to change map settings.
 * Edit config/maps.yml to change district plans, overlays, and tilesets.
 * Set MAPBOX_TOKEN in .env (locally) or as a GitHub Actions secret.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import yaml from 'js-yaml';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root      = resolve(__dirname, '../..');
const publicDir = resolve(__dirname, '../public');

// Load .env from repo root (simple parser — no external dep needed)
function loadDotEnv(envPath) {
  try {
    for (const line of readFileSync(envPath, 'utf8').split('\n')) {
      const m = line.match(/^\s*([A-Z_][A-Z0-9_]*)=(.*)$/);
      if (m && !process.env[m[1]]) {
        process.env[m[1]] = m[2].replace(/^['"]|['"]$/g, '').trim();
      }
    }
  } catch { /* .env is optional */ }
}
loadDotEnv(resolve(root, '.env'));

const mapboxToken = process.env.MAPBOX_TOKEN ?? '';
if (!mapboxToken) {
  console.warn('⚠  MAPBOX_TOKEN not set — set it in .env or as an env var');
}

const config = yaml.load(readFileSync(resolve(root, 'config/config.yml'), 'utf8'));
const maps   = yaml.load(readFileSync(resolve(root, 'config/maps.yml'),   'utf8'));

const out = {
  mapboxToken,
  map:           config.map,
  tilesets:      maps.tilesets,
  districtPlans: maps.districtPlans,
  overlays:      maps.overlays,
  boundaries:    maps.boundaries,
};

mkdirSync(publicDir, { recursive: true });
writeFileSync(resolve(publicDir, 'config.json'), JSON.stringify(out, null, 2));
console.log('✓ config.json baked');

// ── Analytics ──────────────────────────────────────────────────────────────
// Resolution order: env var → config.yml value → empty string (analytics disabled)
const ga4Id      = process.env.GA4_MEASUREMENT_ID ?? config.analytics?.ga4_measurement_id ?? '';
const clarityId  = process.env.CLARITY_PROJECT_ID ?? config.analytics?.clarity_project_id ?? '';

if (!ga4Id)     console.warn('⚠  GA4_MEASUREMENT_ID not set — Google Analytics disabled');
if (!clarityId) console.warn('⚠  CLARITY_PROJECT_ID not set — Microsoft Clarity disabled');

const analyticsJs = `// Auto-generated by bake-config.mjs — do not edit manually
(function () {
  var GA4_ID     = ${JSON.stringify(ga4Id)};
  var CLARITY_ID = ${JSON.stringify(clarityId)};

  // ── Google Analytics 4 ─────────────────────────────────────────────────
  // GA4 automatically reports country/region/city from IP (anonymized).
  // View under Reports → User → Demographics → Location in GA4 console.
  if (GA4_ID) {
    var s = document.createElement('script');
    s.async = true;
    s.src = 'https://www.googletagmanager.com/gtag/js?id=' + GA4_ID;
    document.head.appendChild(s);

    window.dataLayer = window.dataLayer || [];
    function gtag() { window.dataLayer.push(arguments); }
    window.gtag = gtag;
    gtag('js', new Date());
    gtag('config', GA4_ID, {
      anonymize_ip: true,           // mask last octet of IPv4 / last 80 bits of IPv6
    });
    // Also capture browser locale as a user property (language tag, e.g. "en-US")
    gtag('set', 'user_properties', {
      browser_locale: navigator.language || 'unknown',
    });
  }

  // ── Microsoft Clarity ──────────────────────────────────────────────────
  if (CLARITY_ID) {
    (function (c, l, a, r, i, t, y) {
      c[a] = c[a] || function () { (c[a].q = c[a].q || []).push(arguments); };
      t = l.createElement(r); t.async = 1;
      t.src = 'https://www.clarity.ms/tag/' + i;
      y = l.getElementsByTagName(r)[0]; y.parentNode.insertBefore(t, y);
    })(window, document, 'clarity', 'script', CLARITY_ID);
  }
})();
`;

writeFileSync(resolve(publicDir, 'analytics.js'), analyticsJs);
console.log(`✓ analytics.js baked (GA4: ${ga4Id || 'disabled'}, Clarity: ${clarityId || 'disabled'})`);

